export const barangMasuk = [
  {
    id: 1,
    No: "1",
    name: "Mesin pompa air",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "eko",
  },
  {
    id: 2,
    No: "2",
    name: "Mitsubishi",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "ahen",
  },
  {
    id: 3,
    No: "3",
    name: "Organic Landing page",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "eko",
  },
  {
    id: 4,
    No: "4",
    name: "Organic Landing page",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "eko",
  },
  {
    id: 5,
    No: "5",
    name: "Organic Landing page",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "eko",
  },
  {
    id: 6,
    No: "6",
    name: "Organic Landing page",
    harga_beli: "550.000",
    harga_jual: "600.600",
    jumlah_masuk: "5 mesin",
    nama_supplier: "eko",
  },
];
